abstract: ~
author: Agent Zhang <agentzh@gmail.com>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Sim
no_index: 
  directory: 
    - inc
    - t
  sample: []

requires: 
  Carp: 0
  perl: 5.004001
version: 0.01
